language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
sudo: false
script: mkdir /tmp/n && ./configure --prefix=/tmp/n && make && make check && make install

notifications:
  irc:
    channels:
      - "chat.freenode.net#nmap"
    on_success: change
    on_failure: always
