local windows = {
[1] ={
	["name"]="Windows 95 OEM Service Release 1 (95A)",
	["majversion"] ="4",
	["minversion"] ="00",
	["build"] ="950 A",
	["type"] ="Client",
},
[2] ={
	["name"]="Windows 95 OEM Service Release 2 (95B)",
	["majversion"] ="4",
	["minversion"] ="00",
	["build"] ="1111 B",
	["type"] ="Client",
},
[3] ={
	["name"]="Windows 95 OEM Service Release 2.1",
	["majversion"] ="4",
	["minversion"] ="03",
	["build"] ="1212-1214 B",
	["type"] ="Client",
},
[4] ={
	["name"]="Windows 95 OEM Service Release 2.5 C",
	["majversion"] ="4",
	["minversion"] ="03",
	["build"] ="1214 C",
	["type"] ="Client",
},
[5] ={
	["name"]="Windows 98",
	["majversion"] ="4",
	["minversion"] ="10",
	["build"] ="1998",
	["type"] ="Client",
},
[6] ={
	["name"]="Windows 98 Second Edition (SE)",
	["majversion"] ="4",
	["minversion"] ="10",
	["build"] ="2222 A",
	["type"] ="Client",
},
[7] ={
	["name"]="Windows Millenium Beta",
	["majversion"] ="4",
	["minversion"] ="90",
	["build"] ="2476",
	["type"] ="Client",
},
[8] ={
	["name"]="Windows Millenium",
	["majversion"] ="4",
	["minversion"] ="90",
	["build"] ="3000",
	["type"] ="Client",
},
[9] ={
	["name"]="Windows NT 3.1",
	["majversion"] ="3",
	["minversion"] ="10",
	["build"] ="528 ",
	["type"] ="Client",
},
[10] ={
	["name"]="Windows NT 3.5",
	["majversion"] ="3",
	["minversion"] ="50",
	["build"] ="807 ",
	["type"] ="Client",
},
[11] ={
	["name"]="Windows NT 3.51",
	["majversion"] ="3",
	["minversion"] ="51",
	["build"] ="1057 ",
	["type"] ="Client",
},
[12] ={
	["name"]="Windows NT 4.00",
	["majversion"] ="4",
	["minversion"] ="00",
	["build"] ="1381 ",
	["type"] ="Client",
},
[13] ={
	["name"]="Windows NT 5.00 (Beta 2)",
	["majversion"] ="5",
	["minversion"] ="00",
	["build"] ="1515",
	["type"] ="Client",
},
[14] ={
	["name"]="Windows 2000 (Beta 3)",
	["majversion"] ="5",
	["minversion"] ="00",
	["build"] ="2031",
	["type"] ="Client",
},
[15] ={
	["name"]="Windows 2000 (Beta 3 RC2)",
	["majversion"] ="5",
	["minversion"] ="00",
	["build"] ="2128",
	["type"] ="Client",
},
[16] ={
	["name"]="Windows 2000 (Beta 3)",
	["majversion"] ="5",
	["minversion"] ="00",
	["build"] ="2183",
	["type"] ="Client",
},
[17] ={
	["name"]="Windows 2000",
	["majversion"] ="5",
	["minversion"] ="00",
	["build"] ="2195 ",
	["type"] ="Client",
},
[18] ={
	["name"]="Whistler Server Preview",
	["majversion"] ="",
	["minversion"] ="",
	["build"] ="2250",
	["type"] ="Server",
},
[19] ={
	["name"]="Whistler Server alpha",
	["majversion"] ="",
	["minversion"] ="",
	["build"] ="2257",
	["type"] ="Server",
},
[20] ={
	["name"]="Whistler Server interim release",
	["majversion"] ="",
	["minversion"] ="",
	["build"] ="2267",
	["type"] ="Server",
},
[21] ={
	["name"]="Whistler Server interim release",
	["majversion"] ="",
	["minversion"] ="",
	["build"] ="2410",
	["type"] ="Server",
},
[22] ={
	["name"]="Windows XP (RC 1)",
	["majversion"] ="5",
	["minversion"] ="1",
	["build"] ="2505",
	["type"] ="Client",
},
[23] ={
	["name"]="Windows XP",
	["majversion"] ="5",
	["minversion"] ="1",
	["build"] ="2600 ",
	["type"] ="Client",
},
[24] ={
	["name"]="Windows XP, Service Pack 1",
	["majversion"] ="5",
	["minversion"] ="1",
	["build"] ="2600.1105",
	["type"] ="Client",
},
[25] ={
	["name"]="Windows XP, Service Pack 2",
	["majversion"] ="5",
	["minversion"] ="1",
	["build"] ="2600.2180",
	["type"] ="Client",
},
[26] ={
	["name"]="Windows XP, Service Pack 3",
	["majversion"] ="5",
	["minversion"] ="1",
	["build"] ="2600 ",
	["type"] ="Client",
},
[27] ={
	["name"]="Windows .NET Server interim",
	["majversion"] ="5",
	["minversion"] ="2",
	["build"] ="3541",
	["type"] ="Server",
},
[28] ={
	["name"]="Windows .NET Server Beta 3",
	["majversion"] ="5",
	["minversion"] ="2",
	["build"] ="3590",
	["type"] ="Server",
},
[29] ={
	["name"]="Windows .NET Server Release Candidate 1 (RC1)",
	["majversion"] ="5",
	["minversion"] ="2",
	["build"] ="3660",
	["type"] ="Server",
},
[30] ={
	["name"]="Windows .NET Server 2003 RC2",
	["majversion"] ="5",
	["minversion"] ="2",
	["build"] ="3718",
	["type"] ="Server",
},
[31] ={
	["name"]="Windows Server 2003 (Beta?)",
	["majversion"] ="5",
	["minversion"] ="2",
	["build"] ="3763",
	["type"] ="Server",
},
[32] ={
	["name"]="Windows Server 2003",
	["majversion"] ="5",
	["minversion"] ="2",
	["build"] ="3790 ",
	["type"] ="Server",
},
[33] ={
	["name"]="Windows Server 2003, Service Pack 1",
	["majversion"] ="5",
	["minversion"] ="2",
	["build"] ="3790.1180",
	["type"] ="Server",
},
[34] ={
	["name"]="Windows Server 2003",
	["majversion"] ="5",
	["minversion"] ="2",
	["build"] ="3790.1218",
	["type"] ="Server",
},
[35] ={
	["name"]="Windows Home Server",
	["majversion"] ="5",
	["minversion"] ="2",
	["build"] ="3790 ",
	["type"] ="Server",
},
[36] ={
	["name"]="Windows Longhorn",
	["majversion"] ="6",
	["minversion"] ="0",
	["build"] ="5048",
	["type"] ="Client",
},
[37] ={
	["name"]="Windows Vista, Beta 1",
	["majversion"] ="6",
	["minversion"] ="0",
	["build"] ="5112 ",
	["type"] ="Client",
},
[38] ={
	["name"]="Windows Vista, Community Technology Preview (CTP)",
	["majversion"] ="6",
	["minversion"] ="0",
	["build"] ="5219 ",
	["type"] ="Client",
},
[39] ={
	["name"]="Windows Vista, TAP Preview",
	["majversion"] ="6",
	["minversion"] ="0",
	["build"] ="5259 ",
	["type"] ="Client",
},
[40] ={
	["name"]="Windows Vista, CTP (Dezember)",
	["majversion"] ="6",
	["minversion"] ="0",
	["build"] ="5270 ",
	["type"] ="Client",
},
[41] ={
	["name"]="Windows Vista, CTP (Februar)",
	["majversion"] ="6",
	["minversion"] ="0",
	["build"] ="5308 ",
	["type"] ="Client",
},
[42] ={
	["name"]="Windows Vista, CTP (Refresh)",
	["majversion"] ="6",
	["minversion"] ="0",
	["build"] ="5342 ",
	["type"] ="Client",
},
[43] ={
	["name"]="Windows Vista, April EWD",
	["majversion"] ="6",
	["minversion"] ="0",
	["build"] ="5365 ",
	["type"] ="Client",
},
[44] ={
	["name"]="Windows Vista, Beta 2 Previw",
	["majversion"] ="6",
	["minversion"] ="0",
	["build"] ="5381 ",
	["type"] ="Client",
},
[45] ={
	["name"]="Windows Vista, Beta 2",
	["majversion"] ="6",
	["minversion"] ="0",
	["build"] ="5384 ",
	["type"] ="Client",
},
[46] ={
	["name"]="Windows Vista, Pre-RC1",
	["majversion"] ="6",
	["minversion"] ="0",
	["build"] ="5456 ",
	["type"] ="Client",
},
[47] ={
	["name"]="Windows Vista, Pre-RC1, Build 5472",
	["majversion"] ="6",
	["minversion"] ="0",
	["build"] ="5472 ",
	["type"] ="Client",
},
[48] ={
	["name"]="Windows Vista, Pre-RC1, Build 5536",
	["majversion"] ="6",
	["minversion"] ="0",
	["build"] ="5536 ",
	["type"] ="Client",
},
[49] ={
	["name"]="Windows Vista, RC1",
	["majversion"] ="6",
	["minversion"] ="0",
	["build"] ="5600.16384 ",
	["type"] ="Client",
},
[50] ={
	["name"]="Windows Vista, Pre-RC2",
	["majversion"] ="6",
	["minversion"] ="0",
	["build"] ="5700 ",
	["type"] ="Client",
},
[51] ={
	["name"]="Windows Vista, Pre-RC2, Build 5728",
	["majversion"] ="6",
	["minversion"] ="0",
	["build"] ="5728 ",
	["type"] ="Client",
},
[52] ={
	["name"]="Windows Vista, RC2",
	["majversion"] ="6",
	["minversion"] ="0",
	["build"] ="5744.16384 ",
	["type"] ="Client",
},
[53] ={
	["name"]="Windows Vista, Pre-RTM, Build 5808",
	["majversion"] ="6",
	["minversion"] ="0",
	["build"] ="5808 ",
	["type"] ="Client",
},
[54] ={
	["name"]="Windows Vista, Pre-RTM, Build 5824",
	["majversion"] ="6",
	["minversion"] ="0",
	["build"] ="5824 ",
	["type"] ="Client",
},
[55] ={
	["name"]="Windows Vista, Pre-RTM, Build 5840",
	["majversion"] ="6",
	["minversion"] ="0",
	["build"] ="5840 ",
	["type"] ="Client",
},
[56] ={
	["name"]="Windows Vista, RTM (Release to Manufacturing)",
	["majversion"] ="6",
	["minversion"] ="0",
	["build"] ="6000.16386 ",
	["type"] ="Client",
},
[57] ={
	["name"]="Windows Vista",
	["majversion"] ="6",
	["minversion"] ="0",
	["build"] ="6000 ",
	["type"] ="Client",
},
[58] ={
	["name"]="Windows Vista, Service Pack 2",
	["majversion"] ="6",
	["minversion"] ="0",
	["build"] ="6002 ",
	["type"] ="Client",
},
[59] ={
	["name"]="Windows Server 2008",
	["majversion"] ="6",
	["minversion"] ="0",
	["build"] ="6001 ",
	["type"] ="Server",
},
[60] ={
	["name"]="Windows 7, RTM (Release to Manufacturing)",
	["majversion"] ="6",
	["minversion"] ="1",
	["build"] ="7600.16385 ",
	["type"] ="Client",
},
[61] ={
	["name"]="Windows 7",
	["majversion"] ="6",
	["minversion"] ="1",
	["build"] ="7601",
	["type"] ="Client",
},
[62] ={
	["name"]="Windows Server 2008 R2, RTM (Release to Manufacturing)",
	["majversion"] ="6",
	["minversion"] ="1",
	["build"] ="7600.16385 ",
	["type"] ="Server",
},
[63] ={
	["name"]="Windows Server 2008 R2, SP1",
	["majversion"] ="6",
	["minversion"] ="1",
	["build"] ="7601",
	["type"] ="Server",
},
[64] ={
	["name"]="Windows Home Server 2011",
	["majversion"] ="6",
	["minversion"] ="1",
	["build"] ="8400 ",
	["type"] ="Server",
},
[65] ={
	["name"]="Windows Server 2012",
	["majversion"] ="6",
	["minversion"] ="2",
	["build"] ="9200 ",
	["type"] ="Server",
},
[66] ={
	["name"]="Windows 8",
	["majversion"] ="6",
	["minversion"] ="2",
	["build"] ="9200 ",
	["type"] ="Client",
},
[67] ={
	["name"]="Windows Phone 8",
	["majversion"] ="6",
	["minversion"] ="2",
	["build"] ="10211 ",
	["type"] ="Client",
},
[68] ={
	["name"]="Windows Server 2012 R2",
	["majversion"] ="6",
	["minversion"] ="3",
	["build"] ="9200 ",
	["type"] ="Server",
},
[69] ={
	["name"]="Windows 8.1",
	["majversion"] ="6",
	["minversion"] ="3",
	["build"] ="9200 ",
	["type"] ="Client",
},
[70] ={
	["name"]="Windows 8.1, Update 1",
	["majversion"] ="6",
	["minversion"] ="3",
	["build"] ="9600 ",
	["type"] ="Client",
},
}
function get_table()
	return windows
end	